apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pacman
    app.kubernetes.io/instance: pacman
  name: pacman
  namespace: pacman-argo
spec:
  ports:
  - port: 32000
    protocol: TCP
    targetPort: 32000
  selector:
    app: pacman
  type: LoadBalancer
status:
  loadBalancer: {}
